### PR TITLE
Fix latlon_to_str function

### PR DESCRIPTION
**Pull request by mfouilleul**
I had an issue with wrong GPS positions on the tracking (detailed on SA discord https://discordapp.com/channels/622034301470507028/740952035955965993/751884952160698448

This fix only the logbook feature as the NMEA use another format...

### CODE REVIEW

**Comment by musurca** [comment]
thanks!

**Comment by mfouilleul** [comment]
No problem. Can you help me to fix the formula for the NMEA? I can't find a good way to do it.

**Comment by mfouilleul** [comment]
I just so your mentioned on Discord. Thanks for taking NMEA :)

**Comment by musurca** [comment]
Done and just pushed out a new release: https://github.com/musurca/Haddock/releases/download/0.1.2/Haddock_v0.1.2.zip

Thanks again!

**Pull request merged**
